BD1: LigatureLayoutBug
urbn/iOSBugDemos pull request #3
Opened 2018-10-30 22:31 UTC by ncsouvenir

This sample project was made in response to ticket: [UIOS-4682](https://urbnit.atlassian.net/browse/UIOS-4682).

When ligatures are added to a horizontal collection view with fixed height, it breaks the minimum inter--item spacing (horizontal spacing) and cells are placed up against one another.

However, when a horizontal collection view implements a datasource with ligatures, it will ignore the minimum inter-item spacing and default to the minimum line spacing (vertical spacing) which acts as the minimum inter--item spacing(WEIRD!)

This sample project shows examples of three horizontal collection views populated with different datasources and different minimumLineSpacing to show how the datasources with ligatures ignore the  minimum inter-item spacing.

2018-11-01 19:31 UTC, JohnBueno requested changes

2018-11-01 19:31 UTC, JohnBueno commented on LigatureLayoutBug/LigatureLayoutBug/ExampleCollectionView.swift
> +            ])
This code is a bit confusing.  I see that you are trying to set the height of the collectionView but you are also just resetting all of the other anchors to themselves which should in theory have no effect. 

I think you could achieve your purpose with a:

`heightAnchor.constraint(equalToConstant: flowLayout.itemSize.height).isActive = true`

2018-11-01 19:31 UTC, JohnBueno commented on LigatureLayoutBug/LigatureLayoutBug/ExampleView.swift
> +
Can this whole file just be removed?

2018-11-02 13:28 UTC, ncsouvenir commented on LigatureLayoutBug/LigatureLayoutBug/ExampleView.swift
> +
Yes, I just deleted it.

2018-11-02 15:08 UTC, ryang1428 requested changes

2018-11-02 15:08 UTC, ryang1428 commented on LigatureLayoutBug/LigatureLayoutBug/ExampleCollectionView.swift
> +        self.heightAnchor.constraint(equalToConstant: flowLayout.itemSize.height).isActive = true
minor but you don't need all the `self.`s here (after super)

2018-11-02 16:04 UTC, ryang1428 approved these changes

2018-11-02 17:17 UTC, JohnBueno approved these changes

2018-11-02 17:17 UTC, merged